baseURL = "https://areuman.com/"
languageCode = "en-us"
title = "Areum Blog"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "mine"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /kr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Areum An Blog"
weight = 1
languageName = "English"

[Languages.kr]
title = "어쩌다보니 개발자"
weight = 2
languageName = "한국어"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/AreumAn"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Linkedin"
url = "https://www.linkedin.com/in/areum-an-b34a7612b"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-envelope-open'></i> Email"
url = "mailto:areum.an.0928@google.com"
weight = 12
