baseURL = "http://example.org/"
languageCode = "en-us"
title = "Areum Blog"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
